## Notebook-numpy
---

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
print(np.__version__)

1.15.4


In [7]:
# set the seed for random to keep get the same number in another time
def getdata():
    np.random.seed(0)
    a = np.random.rand(4)
    print(a)

In [8]:
getdata()

[0.5488135  0.71518937 0.60276338 0.54488318]


In [9]:
np.random.seed(8)

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('data:\n', a)
print('ndim:{}\nshape:{}\nsize:{}\ndtype:{}'.format(a.ndim, a.shape, a.size, a.dtype))

data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:2
shape:(3, 3)
size:9
dtype:int32


In [14]:
# 3-D
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print('data:\n', a)
print('ndim:{}\nshape:{}\nsize:{}\ndtype:{}'.format(a.ndim, a.shape, a.size, a.dtype))

data:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim:3
shape:(1, 3, 3)
size:9
dtype:int32


In [21]:
# function
print('np.zeros((2,2)):\n', np.zeros((2,2)))
print('np.ones((2,2)):\n', np.ones((2,2)))
print('np.eye(4):\n', np.eye(4))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


| numpy方法 | 解释 |
| :------ | :------| 
|np.random.rand(x, y, z)	|生成一个一维x随机数或生成x x y的随机数组|
|np.random.randn(x, y)	|标准正态分布随机数|
|np.random.randint(low, high, (shape))	|整数随机数|
|np.random.normal(loc, scale, (size))	|从指定正态分布中抽取样本, loc为概率分布的均匀值, 标准差scale|
|np.random.seed(s)|给一个随机数字固定|
|np.randomunifrom(low, high, (size))	|均匀分布的数组, 有小数|
|np.random.shuffle(a)	|将数组a的第0轴(最外维度)进行随机排列(洗牌), 改变数组a, 行边列不变|
|np.random.permutation(a)	|同上, 不改变数组a|
|np.random.choice(a, size=None, replace=False, p=数组a/np.sum(b))	|从一维数组a中以概率p抽取元素，形成size形状新数组，replace表示是否可以重用元素，默认为False，p为抽取概率,本位置越高,抽取概率越高|

In [44]:
# random
np.random.seed(3)
print('np.random.rand():\n', np.random.rand(2,2,3))         # 生成2x2x3的随机数组，数值范围[0, 1]均匀分布
print('np.random.randn():\n',np.random.randn(2,2,3))        # 生成2x2x3的随机数组，数值范围：标准正太分布

np.random.rand():
 [[[0.5507979  0.70814782 0.29090474]
  [0.51082761 0.89294695 0.89629309]]

 [[0.12558531 0.20724288 0.0514672 ]
  [0.44080984 0.02987621 0.45683322]]]
np.random.randn():
 [[[-1.31386475  0.88462238  0.88131804]
  [ 1.70957306  0.05003364 -0.40467741]]

 [[-0.54535995 -1.54647732  0.98236743]
  [-1.10106763 -1.18504653 -0.2056499 ]]]


In [56]:
# 
mu, sigma = 0, 0.1
s = np.random.normal(mu, sigma, (1, 100))
s1 = sigma * np.random.randn(1, 100) + mu